version: '3'
services:
  server:
    container_name: WRUApp-Backend
    restart: always
    build: .
    volumes:
      - .:/apps/WRUApp-Backend
      - ./build:/apps/WRUApp-Backend/build
    ports:
      - '5000:5000'
      - '9229:9229'
    command: bash -c "npm i && npm run start:dev"
    links:
      - mongodb-primary
  mongodb-primary:
    container_name: mongo
    image: bitnami/mongodb
    volumes:
      - 'dbdata:/data/db'
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_USERNAME: bruce
      MONGODB_PASSWORD: 1234
      MONGODB_DATABASE: wru-db
      # MONGO_INITDB_ROOT_USERNAME: 'bruce'
      # MONGO_INITDB_ROOT_PASSWORD: '1234'
      MONGODB_SECONDARY_PORT_NUMBER: 27018
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_REPLICA_SET_NAME: rs0
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    #entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']

  mongodb-secondary:
    container_name: mongo-replica-1
    image: bitnami/mongodb
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-secondary
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_PRIMARY_HOST: mongodb-primary
      MONGODB_PRIMARY_PORT_NUMBER: 27017
      # MONGODB_ROOT_PASSWORD: 5041
      MONGODB_PRIMARY_ROOT_PASSWORD: password123
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    #entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']
volumes:
  dbdata:
# rs.initiate(   {     _id : 'rs0',     members: [       { _id : 0, host : "mongodb-primary:27017" },       { _id : 1, host : "mongo-replica-1:27018" }     ]   } )

